### ISSUE TITLE
This will cause youtube to detect ublock origin

### ISSUE THREAD

**Issue by federicorosso1993** [x0a/uBO-YouTube#52]
I'm using this to deactivate ublock origin when I'm watching videos from some youtube channels that I think deserve my support. Problem is today I got the "3 videos and we will deactivate youtube" popup (now "Ad blockers violate YouTube's Terms of Service
It appears you are using an ad blocker. Video playback is blocked if YouTube is not whitelisted or if ad blocking is not turned off.
Ads enable billions of people around the world to use YouTube.
Watch videos without ads with YouTube Premium. Creators will continue to generate revenue from your subscription.")

The first thing I did was update my filters but the problem was still there.
After that I tried to deactivate each of my current youtube extension and when I deactivated "YouTube Channel Whitelist for uBlock Origin" the popup was gone.
Can you try to fix it? I actually would like to support my favourite youtube channel, but there is no reason to keep ads activated for videos that already got sponsorship or when I'm just browsing and trying to find the correct video.
And I prefer to avoid keeping ublock always active even when it is not necessary.

Thank you

**Comment by varappdev** [comment]
Same here, just caused ublock to be detected with the most recent script update.

**Comment by a0193143** [comment]
It seems fixed by uBlock Origin itself, now this extension could work without youtube's detection.

**Comment by federicorosso1993** [comment]
> It seems fixed by uBlock Origin itself, now this extension could work without youtube's detection.

I tried it again... for like one time it was working but after I got to my original settings (my whitelist was empty for some reason) it was detected again. So I had to disable it again. So no, it is not fixed.

**Comment by ponko2MSL** [comment]
It worked fine for me for a long while (as long as uBO was up to date with the latest YouTube script), but yesterday YouTube started detecting my adblocker. When I disabled the whitelist add-on, I could watch videos undetected again.

**Comment by KonstSchob** [comment]
Sometimes youtube detects the adblocker. I circumvent this by enabling "force whitelist when loading page for the first time" (idk the actual english name) in the settings. Refreshing any page gets rid of the popup with ads or no ads shown, depending on configuration
